CREATE TABLE pizzas
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    price INTEGER                                 NOT NULL,
    CONSTRAINT pk_pizzas PRIMARY KEY (id)
);