CREATE TABLE order_pizza_id
(
    order_id BIGINT NOT NULL,
    pizza_ids BIGINT
);

CREATE TABLE orders
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    address VARCHAR(255),
    phone   VARCHAR(255),
    status  VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE order_pizza_id
    ADD CONSTRAINT fk_order_pizza_id_on_order FOREIGN KEY (order_id) REFERENCES orders (id);