CREATE TABLE payments
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id                  BIGINT                                  NOT NULL,
    amount                    DECIMAL(10,2)                           NOT NULL,
    currency                  VARCHAR(255)                            NOT NULL,
    payment_method            VARCHAR(255),
    status                    VARCHAR(255),
    yookassa_payment_id       VARCHAR(255),
    yookassa_confirmation_url VARCHAR(255),
    confirmation_url          VARCHAR(255),
    idempotence_key           VARCHAR(255),
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    metadata                  TEXT,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_idempotencekey UNIQUE (idempotence_key);